[package]
name = "rust_access"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odbc = "0.17.0"
odbc-sys = "0.8.2"
odbc-safe = "0.5.0"
env_logger = "0.7"